kind: pipeline
name: Publish

trigger:
  branch:
    - main

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: dorin1025/p-test
    username:
      from_secret: username
    password:
      from_secret: password
    tags: 1 
---
kind: pipeline
name: Publish Notification

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: notify
    template: >
      {{#success build.status}}
          `{{repo.name}}/{{build.branch}}`: Build #{{build.number}} successful 
        {{else}}
          `{{repo.name}}/{{build.branch}}`: Build #{{build.number}} failed 
        {{/success}}
trigger:
  status:
  - success
  - failure

depends_on:
- Publish
---
kind: pipeline
name: Deploy

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 34.125.46.89
    username: root
    password:
      from_secret: ssh_pass
    port: 22
    script:
      - cd /push/push-core && git pull origin main
      - cd /push/push-core && docker-compose down
      - docker rmi dorin1025/p-test:1
      - cd /push/push-core && docker-compose up -d
trigger:
  status:
  - success

depends_on:
- Publish
---  
kind: pipeline
name: Deploy Notification

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: notify
    template: >
      {{#success build.status}}
          `{{repo.name}}/{{build.branch}}`: SSH commands successful
        {{else}}
          `{{repo.name}}/{{build.branch}}`: SSH commands failed
        {{/success}}

trigger:
  status:
  - success
  - failure

depends_on:
- Deploy
