kind: pipeline
name: Deploy

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 161.97.100.77
    username: 
      from_secret: ssh_user
    password:
      from_secret: ssh_pass
    port: 22
    script:
      - cd "C:\Certbot\testdeploy" && git pull origin main && exit
trigger:
  status:
  - success



